import React, { useEffect } from "react";
import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>🌍 Flag-Guessing 🌍</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className=" grid place-content-center text-center mt-96">
          <h1 className=" text-5xl animate-bounce opacity-20">
            [Choose from 3 options what Country showed flag belongs to!]
          </h1>
          <Link href="/Game">
            <button
              onMouseOver={setButtonStyle}
              onMouseLeave={setButtonStyle}
              className={isGreen ? buttonStylingGreen : buttonStylingGray}
            >
              Restart
            </button>
          </Link>
        </div>
      </main>
    </>
  );
}
