import React, { useEffect } from "react";
import Head from "next/head";

export default function Home() {
  // Functions
  useEffect(() => {
    window.onbeforeunload = function () {
      setTimeout(() => {
        window.location.replace("/Gaming");
      }, 5000);
    };
    return () => {
      setTimeout(() => {
        window.location.replace("/Gaming");
      }, 5000);
    };
  }, []);
  // Functions End
  return (
    <>
      <Head>
        <title>Flag Guesser 🌍</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className=" grid place-content-center text-center mt-96">
          <h1 className=" text-5xl animate-bounce opacity-10">
            [Choose from 3 options what Country showed flag belongs to!]
          </h1>
        </div>
      </main>
    </>
  );
}
